routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function() {
  Route::get('/settings', 'SettingController@showSettings')->name('settings');
  Route::post('/setwebhook', 'SettingController@setwebhook')->name('setwebhook');
  Route::post('/settings', 'SettingController@save_settings')->name('settings.store');
  Route::resource('/telusers', 'TeluserController');
  Route::resource('/merchants', 'MerchantController');
  Route::resource('/services', 'ServiceController');
  Route::resource('/portfolios', 'PortfolioController');
  Route::resource('/orders', 'OrderController');
  Route::post('/store', 'StoreController@store')->name('store');
  Route::get('/statistics', 'StatisticController@index')->name('statistics');
  Route::get('/push', 'PushController@index')->name('push');
  Route::post('/sendpush', 'PushController@send')->name('sendpush');
});

Route::post('746136767:AAEladwdXWukscggEwEFiVadBd_yICgdts0', function() {
  app('App\Http\Controllers\TelegramController')->webhookHandler();
})->name('bot-webhook');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{

  protected $fillable = ['title', 'price', 'description', 'merchant_id'];

  public function merchant() {
    return $this->belongsTo('App\Merchant');
  }

  public function portfolios() {
    $this->hasMany('App\Portfolio');
  }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use App\Merchant;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    return view('admin.services.index', [
      'data' => Service::with('merchant')->orderBy('created_at', 'desc')->get()
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('admin.services.create', [
      'data'      => [],
      'merchants' => Merchant::get()->toArray()
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $service = Service::create($request->all());

    return redirect()->route('admin.services.index');
  }

  /**
   * Display the specified resource.
   *
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $service = Service::findOrFail($id);
    return view('admin.services.edit', [
      'data'      => $service,
      'merchants' => Merchant::get()->toArray()
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $service = Service::findOrFail($id);
    $service->update($request->all());

    return redirect()->route('admin.services.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    Service::destroy($id);

    return redirect()->route('admin.services.index');
  }
}

resources/views/admin/services/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <service-form 
        :service="{{ json_encode($data) }}"
        :merchants="{{ json_encode($merchants) }}"
        :csrf_token="{{ json_encode(csrf_token()) }}" 
        :action="{{ json_encode(route('admin.services.store'))}}"
      >
      </service-form>
    </div>
  </div>
</div>
@endsection

resources/views/admin/services/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <service-form
        :service="{{ json_encode($data) }}"
        :merchants="{{ json_encode($merchants) }}"
        :csrf_token="{{ json_encode(csrf_token()) }}"
      >
      </service-form>
    </div>
  </div>
</div>
@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <services-table 
    :data="{{ json_encode($data) }}"
    :create="{{ json_encode(route('admin.services.create')) }}"
    :csrf_token="{{ json_encode(csrf_token()) }}" 
  ></services-table>
</div>
@endsection