routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function() {
  Route::get('/settings', 'SettingController@showSettings')->name('settings');
  Route::post('/setwebhook', 'SettingController@setwebhook')->name('setwebhook');
  Route::post('/settings', 'SettingController@save_settings')->name('settings.store');
  Route::resource('/telusers', 'TeluserController');
  Route::resource('/merchants', 'MerchantController');
  Route::resource('/services', 'ServiceController');
  Route::resource('/portfolios', 'PortfolioController');
  Route::resource('/orders', 'OrderController');
  Route::post('/store', 'StoreController@store')->name('store');
  Route::get('/statistics', 'StatisticController@index')->name('statistics');
  Route::get('/push', 'PushController@index')->name('push');
  Route::post('/sendpush', 'PushController@send')->name('sendpush');
});

Route::post('746136767:AAEladwdXWukscggEwEFiVadBd_yICgdts0', function() {
  app('App\Http\Controllers\TelegramController')->webhookHandler();
})->name('bot-webhook');

resources/views/admin/push.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <push-notification-form
        :action="{{ json_encode(route('admin.sendpush')) }}"
        :csrf_token="{{ json_encode(csrf_token()) }}" 
      ></push-notification-form>
  </div>
  </div>
</div>
@endsection

resources/views/admin/settings.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <settings-form
        :setwebhook="{{ json_encode(route('admin.setwebhook')) }}"
        :save="{{ json_encode(route('admin.settings.store')) }}"
        :csrf_token="{{ json_encode(csrf_token()) }}" 
        :is_admin="{{ json_encode($is_admin) }}"
        :settings="{{ json_encode($settings) }}"
      ></settings-form>
  </div>
  </div>
</div>
@endsection

resources/views/admin/statistics.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <statistic-page
      ></statistic-page>
    </div>
  </div>
</div>
@endsection