routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function() {
  Route::get('/settings', 'SettingController@showSettings')->name('settings');
  Route::post('/setwebhook', 'SettingController@setwebhook')->name('setwebhook');
  Route::post('/settings', 'SettingController@save_settings')->name('settings.store');
  Route::resource('/telusers', 'TeluserController');
  Route::resource('/merchants', 'MerchantController');
  Route::resource('/services', 'ServiceController');
  Route::resource('/portfolios', 'PortfolioController');
  Route::resource('/orders', 'OrderController');
  Route::post('/store', 'StoreController@store')->name('store');
  Route::get('/statistics', 'StatisticController@index')->name('statistics');
  Route::get('/push', 'PushController@index')->name('push');
  Route::post('/sendpush', 'PushController@send')->name('sendpush');
});

Route::post('746136767:AAEladwdXWukscggEwEFiVadBd_yICgdts0', function() {
  app('App\Http\Controllers\TelegramController')->webhookHandler();
})->name('bot-webhook');

app/Merchant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Merchant extends Model
{
  protected $fillable = ['title', 'address', 'number', 'description'];

  public function services() {
    $this->hasMany('App\Service');
  }
}

app/Http/Controllers/MerchantController.php
<?php

namespace App\Http\Controllers;

use App\Merchant;
use Illuminate\Http\Request;

class MerchantController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    return view('admin.merchants.index', [
      'data' => Merchant::orderBy('created_at', 'desc')->get()
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('admin.merchants.create', [
      'data' => []
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $merchant = Merchant::create($request->all());

    return redirect()->route('admin.merchants.index');
  }

  /**
   * Display the specified resource.
   *
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $merchant = Merchant::findOrFail($id);
    return view('admin.merchants.edit', [
      'data' => $merchant
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $merchant = Merchant::findOrFail($id);
    $merchant->update($request->all());

    return redirect()->route('admin.merchants.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    Merchant::destroy($id);

    return redirect()->route('admin.merchants.index');
  }
}

resources/views/admin/merchants/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <merchant-form 
        :merchant="{{ json_encode($data) }}"
        :csrf_token="{{ json_encode(csrf_token()) }}" 
        :action="{{ json_encode(route('admin.merchants.store'))}}"
      >
      </merchant-form>
    </div>
  </div>
</div>
@endsection

resources/views/admin/merchants/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <merchant-form
        :merchant="{{ json_encode($data) }}"
        :csrf_token="{{ json_encode(csrf_token()) }}"
      >
      </servmerchantice-form>
    </div>
  </div>
</div>
@endsection

resources/views/admin/merchants/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <merchants-table 
    :data="{{ json_encode($data) }}"
    :create="{{ json_encode(route('admin.merchants.create')) }}"
    :csrf_token="{{ json_encode(csrf_token()) }}" 
  ></merchants-table>
</div>
@endsection