routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function() {
  Route::get('/settings', 'SettingController@showSettings')->name('settings');
  Route::post('/setwebhook', 'SettingController@setwebhook')->name('setwebhook');
  Route::post('/settings', 'SettingController@save_settings')->name('settings.store');
  Route::resource('/telusers', 'TeluserController');
  Route::resource('/merchants', 'MerchantController');
  Route::resource('/services', 'ServiceController');
  Route::resource('/portfolios', 'PortfolioController');
  Route::resource('/orders', 'OrderController');
  Route::post('/store', 'StoreController@store')->name('store');
  Route::get('/statistics', 'StatisticController@index')->name('statistics');
  Route::get('/push', 'PushController@index')->name('push');
  Route::post('/sendpush', 'PushController@send')->name('sendpush');
});

Route::post('746136767:AAEladwdXWukscggEwEFiVadBd_yICgdts0', function() {
  app('App\Http\Controllers\TelegramController')->webhookHandler();
})->name('bot-webhook');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </script>
</head>
<body>
    <v-app id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                    @auth
                      <li><a class="nav-link" href="{{ route('admin.telusers.index') }}">{{ __('Пользователи') }}</a></li>
                      <li><a class="nav-link" href="{{ route('admin.merchants.index') }}">{{ __('Салоны') }}</a></li>
                      <li><a class="nav-link" href="{{ route('admin.services.index') }}">{{ __('Услуги') }}</a></li>
                      <li><a class="nav-link" href="{{ route('admin.portfolios.index') }}">{{ __('Портфолио') }}</a></li>
                      <li><a class="nav-link" href="{{ route('admin.orders.index') }}">{{ __('Заказы') }}</a></li>
                      <li><a class="nav-link" href="{{ route('admin.statistics') }}">{{ __('Статистика') }}</a></li>
                      <li><a class="nav-link" href="{{ route('admin.settings') }}">{{ __('Настройки') }}</a></li>
                    @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </v-app>
</body>
</html>